const dataItems = [
	"ualiKWcr980",
	"NfP8PDRJ5kz",
	"sgHAhm7vULD",
	"vgouAHz7zaH",
	"Q7cMuUaVLbq",
	"GGUHT3mvxbY",
	"KDlwxTL90MZ",
	"UNIIPVLtCF5",
	"cBve38fC2PZ",
	"RXi7IIN8Z91",
	"gsA12j7KDMZ",
	"QQiOkZCjrIv",
	"w1eITiWwViM",
	"V13yqmtrpPA",
	"J13JpTm7DOU",
	"E0QBhdQXp0H",
	"lB6WyR6AFhz",
	"UVFl1NtLHER",
	"Ju90mAPZd3x",
	"ZrMuzvHy9qg",
	"VuYm1uJDWkd",
	"oZfxcY9WeK9",
	"EwsKQln3VBp",
	"Z84c6Gv2XhI",
	"cQ6wBEGP6vS",
	"gHk5ORWf4aE",
	"rmFaoHCGl2b",
	"rRvMzqsb9By",
	"UcBnRoPKjmW",
	"x1btCd5UuKf",
	"CBzYOVtR0kA",
	"qTo51K1Ud2s",
	"ULMsG8yi8wt",
	"bJPrGY3BFIn",
	"KVxda2BJ3rs",
	"ziqUm2jgxAh",
	"cZOORRi9rUm",
	"oowROW7lCI0",
	"HL0McVLS08N",
	"W4ShgFUzwGO",
	"Z8IWXvZDaDb",
	"qI1iFBgJLUE",
	"ITD880sZumj",
	"P5xOO0F1oI5",
	"Dot3QNpzqVX",
	"FM3omS0laE0",
	"do90jhdAD90",
	"eiBhuN9ODEi",
	"pTKyXWuH87L",
	"SXSH20gmIlH",
	"hTgCHIh3LDi",
	"VLlsXvEFAjm",
	"nC0C9tsOVPq",
	"Oc0fzqdPmTO",
	"emsdMud8kLI",
	"Qoizf3csPD1",
	"X7lCGEW5oTq",
	"grJ2dBBUILS",
	"zfLUqIvZ3Ss",
	"kExkudJmn1J",
	"IchEmxrUGB8",
	"ANrCygrttuH",
	"iBW4VbQkB53",
	"E6Cj9aDxZ7Z",
	"vGLuchbWhH0",
];

const mapping = dataItems.map((item) => {
	return {
		sourceId: item,
		id: item,
	};
});

console.log(JSON.stringify(mapping, null, 2));
